# Generated by Django 4.2 on 2023-04-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SongPairing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("song_key", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SongValues",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("song_uri", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=50)),
                (
                    "song_pairings",
                    models.ManyToManyField(
                        blank=True,
                        related_name="song_pairings",
                        to="linkifyapp.songpairing",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="songpairing",
            name="song_values",
            field=models.ManyToManyField(
                blank=True, related_name="song_values", to="linkifyapp.songvalues"
            ),
        ),
    ]
