# Generated by Django 4.2 on 2023-06-12 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SongPairing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("song_key", models.CharField(max_length=100)),
                ("song_value", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("username", models.CharField(max_length=50)),
                ("token", models.CharField(blank=True, max_length=250)),
                (
                    "song_pairings",
                    models.ManyToManyField(
                        blank=True, related_name="users", to="linkifyapp.songpairing"
                    ),
                ),
            ],
        ),
    ]
