# Generated by Django 4.2 on 2023-04-18 19:36

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SongPairing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("song_key", models.CharField(max_length=100)),
                ("song_values", jsonfield.fields.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=50)),
                (
                    "song_pairings",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="song_pairings",
                        to="linkifyapp.songpairing",
                    ),
                ),
            ],
        ),
    ]
