# Generated by Django 4.2 on 2023-04-19 07:03

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("linkifyapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="songpairing",
            name="song_values",
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name="user",
            name="song_pairings",
            field=models.ManyToManyField(
                blank=True, related_name="song_pairings", to="linkifyapp.songpairing"
            ),
        ),
    ]
